services:
  - type: web
    name: lightit-backend
    env: node
    plan: free
    branch: main
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: MONGO_URI
        value: your-mongo-uri
      - key: JWT_SECRET
        value: your-secret
      - key: NODE_ENV
        value: production

  - type: web
    name: lightit-frontend
    env: static
    plan: free
    branch: main
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    autoDeploy: true
    envVars:
      - key: REACT_APP_API_URL
        value: https://lightit-backend.onrender.com
