services:
  - type: web
    name: lightit-backend
    runtime: node
    plan: starter
    branch: main
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://akorvikkyy:hreYwhUbcReXBF2d@cluster0.mbvxjel.mongodb.net/lightitdb?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: 9f1c4b1e2a3c4d5e6f7a8b9c0d1e2f3a
      - key: NODE_ENV
        value: production

  - type: web
    name: lightit-frontend
    runtime: node
    plan: starter
    branch: main
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build
    autoDeploy: true
    envVars:
      - key: REACT_APP_API_URL
        value: https://lightit-backend.onrender.com
