services:
  - type: web
    name: lightit-backend
    runtime: node
    plan: free
    branch: main
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: MONGO_URI
        value: your-mongo-uri
      - key: JWT_SECRET
        value: your-secret
      - key: NODE_ENV
        value: production